version: '3'

services:
  fastapi:
    container_name: fastapi
    restart: always
    image: mclub4/fastapi
    env_file:
      - .env
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "8000:8000"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge