name: Deploy Server

on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  setup-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo DB_ENDPOINT=HI >> .env

      - name: Copy .env to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          source: "./.env"
          target: "winkton"

      - name: Copy docker-compose.yaml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          source: "./docker-compose.yml"
          target: "winkton"

  build-fastapi:
    runs-on: ubuntu-latest
    needs: setup-env

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push FastAPI
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/fastapi:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on : ubuntu-latest
    needs: [build-fastapi]

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            if [ "$(sudo docker ps -qa)" ]; then
              sudo docker rm -f $(sudo docker ps -qa)
            fi
            
            sudo docker pull ${{ secrets.DOCKER_REPO }}/fastapi:latest
            
            sudo docker compose -f winkton/docker-compose.yml up -d
            sudo docker image prune -f
